#!/usr/bin/perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
#     Script to merge the generated APL script with chunks from other origin
#     Copyright (C) 2015, 2016 Jean Forget
#
#     This program is distributed under the GNU Public License version 1 or later
#
#     You can find the text of the license in the F<LICENSE> file or at
#     L<http://www.gnu.org/licenses/gpl-1.0.html>.
#
#     Here is the summary of GPL:
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 1, or (at your option)
#     any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software Foundation,
#     Inc., L<http://www.fsf.org/>.
#

use utf8;
use v5.10;
use strict;
use warnings;
use DateTime;
use HTML::TokeParser;

my $script_av    = 'calendar-french.apl-1';
my $script_ap    = 'workspaces/calfr.apl';
my $script_nars  = 'workspaces/calfrnars.apl';
my $testdata     = 'testapl';
my $teststring   = 'testapl1';
my $feasts       = 'feasts';

open my $av, '<:encoding(UTF-8)', $script_av
  or die "opening $script_av $!";
open my $ap, '>:encoding(UTF-8)', $script_ap
  or die "opening $script_ap $!";
open my $nars, '>:encoding(UTF-8)', $script_nars
  or die "opening $script_nars $!";

# Portability issue: maybe apl is installed in another directory
print $ap   "#!/usr/bin/apl -f\n";
print $nars "#!/usr/bin/apl -f\n";

while (<$av>) {
  print $ap $_;
  print $nars remove_accents($_);
  if (/include here the contents of testapl(?!1)/) {
    open my $sc, '<:encoding(UTF-8)', $testdata
      or die "opening $testdata $!";
    while (<$sc>) {
      print $ap $_;
      print $nars remove_accents($_);
    }
    close $sc
      or die "Closing $testdata $!";
  }
  elsif (/include here the contents of testapl1/) {
    open my $sc, '<:encoding(UTF-8)', $teststring
      or die "opening $teststring $!";
    while (<$sc>) {
      print $ap $_;
      print $nars remove_accents($_);
    }
    close $sc
      or die "Closing $teststring $!";
  }
  elsif (/include here the contents of feasts/) {
    open my $sc, '<:encoding(UTF-8)', $feasts
      or die "opening $feasts $!";
    while (<$sc>) {
      print $ap $_;
      print $nars remove_accents($_);
    }
    close $sc
      or die "Closing $feasts $!";
  }
  elsif (/^∇$/) {
    print $ap   "\n";
    print $nars "\n";
  }
}

close $av
  or die "Closing $script_av $!";
close $ap
  or die "Closing $script_ap $!";
close $nars
  or die "Closing $script_nars $!";

sub remove_accents {
  my ($ln) = @_;
  $ln =~ s/œ(.*) '/oe$1'/;
  $ln =~ s/Œ(.*) '/Oe$1'/;
  $ln =~ tr/ÂÉàâèéêëîïôû/AEaaeeeeiiou/;
  $ln;
}

